name: "Rust CI"
on:
  pull_request:

jobs:
  build:
    name: cargo build and test
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2023-09-20
      - run: cargo build --verbose --release
      - run: cargo test --verbose --release --all

  formatting:
    name: cargo fmt
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
